server:
    port: 8088
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/youran?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: root
logging:
    level:
        root: info
        java:
            sql: debug
        com:
            youran: debug

youran:
    # 缓存数据目录，用来临时存储模板文件、生成的代码文件，每次启动都会清空该目录
    data-dir: D:\\youran
    # 启动时初始化用户表
    default-user-init: true
